spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tttppp606/config-repo.git
          force-pull: true   #强制拉取
#          username:
#          password:
#          search-paths:

server:
  port: 60000
